### PR TITLE
Fix combat voice audio element calls

### LINKED ISSUE #842: [Issue]: Client build fails — `HTMLAudioElement.stop / setVolume / setMuted` don't exist (regression in fd768bfe)
## Summary

Client build is broken on `main` (`fd768bfe` "rizz"). `pnpm --filter @marinara-engine/client run build` fails with three TS errors in `packages/client/src/components/game/GameCombatUI.tsx`, because the commit calls `stop()` / `setVolume()` / `setMuted()` on a `combatVoiceAudioRef` that is typed as (and holds) a raw `HTMLAudioElement`, which has none of those methods.

## Expected behavior

`pnpm check` (and the client build it runs) passes on `main`.

## Actual behavior

```
src/components/game/GameCombatUI.tsx(732,35): error TS2339: Property 'stop' does not exist on type 'HTMLAudioElement'.
src/components/game/GameCombatUI.tsx(844,33): error TS2551: Property 'setVolume' does not exist on type 'HTMLAudioElement'. Did you mean 'volume'?
src/components/game/GameCombatUI.tsx(845,33): error TS2339: Property 'setMuted' does not exist on type 'HTMLAudioElement'.
ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @marinara-engine/client@1.5.9 build: `tsc -b && vite build`
```

Root cause: in `fd768bfe`, the three call sites were refactored from direct `HTMLAudioElement` property access (`.pause()` / `.volume = …` / `.muted = …`) to method calls that only exist on the `OneShotAudioLayer` / `LoopingAudioLayer` handle interfaces in `packages/client/src/lib/game-audio.ts:30-34`. `combatVoiceAudioRef` is still `useRef<HTMLAudioElement | null>(null)` (line 634) and assigned via `new Audio(url)` (line 781), so the calls don't compile.

Note: the rest of the same commit DID use the new `audioManager` surface correctly on the creation path — `audioManager.unlock()` (line 747) and `audioManager.setMediaElementVolume(audio, …)` (line 783). The three failing call sites look like a missed pass of the same refactor.

## Steps to reproduce

1. Check out `main` at `fd768bfe`.
2. `pnpm install --frozen-lockfile`
3. `pnpm --filter @marinara-engine/client run build` (or just `pnpm check`).
4. See the three errors above.

## Environment

- Marinara Engine version: 1.5.9 (commit `fd768bfe` on `main`)
- Install type: source
- OS + version: Windows 11
- Browser or app shell: n/a — build-time, not runtime

## Logs, screenshots, or video

See "Actual behavior" above for the full `tsc` output.

## Additional context

The published `v1.5.9` tag is at `1968e5b6`, which predates `fd768bfe` and `ba27f75f` ("Add TTS playback controls", #715), so released artifacts are unaffected. The breakage only hits anyone building from `main` (including any autoDeploy pipeline pointed at `main`).

Fix is straightforward — restore the three call sites to the `HTMLAudioElement` surface that the rest of the component already uses (line 821 already calls `.pause()` directly; the creation path on line 784 already sets `.muted` directly; the volume update can route through `audioManager.setMediaElementVolume(...)` to match line 783). PR incoming.

## Template check

- [ ] I DID NOT read this template and provide the requested details.

### PR DESCRIPTION
**Pull request by cha1latte**
## Linked issue

Closes #842

## Why this change

- `upstream/main` currently fails `pnpm build` in `GameCombatUI.tsx` because combat voice playback stores a browser `HTMLAudioElement` but calls custom audio-layer methods on it: `stop`, `setVolume`, and `setMuted`.

## What changed

- Stops combat voice playback with valid `HTMLAudioElement` APIs: `pause()`, cleared event handlers, and a nulled ref.
- Keeps the newer audio manager volume path by using `audioManager.setMediaElementVolume(...)`.
- Updates mute state through the native `HTMLAudioElement.muted` property.

## Validation

- [ ] `pnpm check` passes locally
- [ ] Container (Docker / Podman) built and ran without issue
- [ ] Ran the app, clicked through the changes manually
- [ ] Checked edge cases (light + dark mode, mobile viewport, empty states, error paths)
- [ ] Above manual verification completed (describe below)
- [ ] Read and followed `CONTRIBUTING.md`

### Manual verification notes

- Reproduced the failure with `pnpm --filter @marinara-engine/client build`; it failed on `HTMLAudioElement.stop`, `setVolume`, and `setMuted`.
- After the fix, `pnpm --filter @marinara-engine/client build` passed.
- After the fix, `pnpm check` passed.
- Local Docker container verification was not run because Docker Desktop / the Linux engine was not available on this machine.

## Docs and release impact

- [ ] No docs changes needed
- [ ] Updated docs (README / CONTRIBUTING / android/README / CHANGELOG) as needed
- [ ] Version/release files updated (only if this PR includes a version bump)

No docs, release metadata, schema, dependency, or version files changed.

## UI evidence (if applicable)

N/A — this is a TypeScript build fix for combat voice playback.

### CODE REVIEW

**Comment by cha1latte** [comment]
@coderabbitai review

**Comment by Romuromylus** [comment]
Same fix I landed on in #844 — closed mine as a duplicate since this one was filed first.

For tracker hygiene: this also resolves #842 (the issue I filed against the regression with the full repro + root cause). Will add `Closes #842` to the PR body, it'll auto-close the issue on merge.

Also manually tested it on my end, should be working :)
